name: Mirror to SourceForge

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCEFORGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa slickstack.git.sourceforge.net >> ~/.ssh/known_hosts

      - name: Push to SourceForge
        run: |
          git remote add sourceforge ssh://jessuppi@slickstack.git.sourceforge.net/gitroot/slickstack/slickstack
          git push sourceforge master
